/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoo;

import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Carlos
 */
public class Hub extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    Métodos métodos = new Métodos();
    
    /**
     * Creates new form NewJFrame
     */
    public boolean isNormalUser = false;
    public Hub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Integrantes = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        PanelControl = new javax.swing.JPanel();
        BCargar = new javax.swing.JButton();
        BTabla = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NSeccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NMateria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NDocente = new javax.swing.JTextField();
        PanelInformacion = new javax.swing.JPanel();
        LabelSeccion1 = new javax.swing.JLabel();
        LabelMateria1 = new javax.swing.JLabel();
        LabelDocente1 = new javax.swing.JLabel();
        LabelPromedio1 = new javax.swing.JLabel();
        LabelAprobados = new javax.swing.JLabel();
        logohub = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Calificaciones Escolar");

        Integrantes.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Integrantes.setText("Carlos Gutiérrez y Enrique Hidalgo");

        PanelTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Primer corte", "Segundo corte", "Definitiva"
            }
        ));
        jScrollPane1.setViewportView(Tabla2);

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelControl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BCargar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BCargar.setText("Cargar Tabla");
        BCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarActionPerformed(evt);
            }
        });

        BTabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTabla.setText("Crear y Modificar Tablas");
        BTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTablaActionPerformed(evt);
            }
        });

        jLabel5.setText("Sección:");

        jLabel6.setText("Materia:");

        jLabel7.setText("Docente:");

        javax.swing.GroupLayout PanelControlLayout = new javax.swing.GroupLayout(PanelControl);
        PanelControl.setLayout(PanelControlLayout);
        PanelControlLayout.setHorizontalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(BCargar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NSeccion)
                    .addComponent(NDocente)
                    .addComponent(NMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        PanelControlLayout.setVerticalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        PanelInformacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelSeccion1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelSeccion1.setText("Sección:");

        LabelMateria1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelMateria1.setText("Materia:");

        LabelDocente1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelDocente1.setText("Docente:");

        LabelPromedio1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelPromedio1.setText("Promedio General:");

        LabelAprobados.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelAprobados.setText("% de Aprobados:");

        logohub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoyextras/urbelogo2.png"))); // NOI18N

        javax.swing.GroupLayout PanelInformacionLayout = new javax.swing.GroupLayout(PanelInformacion);
        PanelInformacion.setLayout(PanelInformacionLayout);
        PanelInformacionLayout.setHorizontalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logohub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSeccion1)
                    .addComponent(LabelDocente1)
                    .addComponent(LabelMateria1)
                    .addComponent(LabelPromedio1)
                    .addComponent(LabelAprobados))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        PanelInformacionLayout.setVerticalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(LabelSeccion1)
                        .addGap(22, 22, 22)
                        .addComponent(LabelMateria1)
                        .addGap(18, 18, 18)
                        .addComponent(LabelDocente1)
                        .addGap(92, 92, 92)
                        .addComponent(LabelPromedio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelAprobados))
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logohub)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addComponent(Integrantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Sección de código correspondiente al botón de editar tablas.
    private void BTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTablaActionPerformed
        //Si el usuario posee privilegios de edición, podrá acceder al formulario a través de este botón.
        if(!isNormalUser){
            Formulario acceso = new Formulario();
            acceso.setVisible(true);
        }
    }//GEN-LAST:event_BTablaActionPerformed

    //Sección de código correspondiente al botón de cargar tablas.
    private void BCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarActionPerformed
        
        //Estos string sirven para construir la ruta del archivo.
        String carpeta = "archivos\\";
        String tipo = ".txt";
        //Este string almacenará el nombre del archivo.
        String archivo = NSeccion.getText()+" - "+NMateria.getText()+" - "+NDocente.getText();
        //Este string concatenará los string previamente asignados para almacenarlos en la variable filePath.
        String filePath = carpeta+archivo+tipo;
        
        //Se crea el objeto file con los parámetros de filePath.
        File file = new File(filePath);
        
        
        ArrayList<Float> promedios = new ArrayList<>();
        float promedioSeccion = 0;
        int aprobados = 0;
        
        //Se almacena en un vector la información del string almacenado en archivo.
        String seccion2 = archivo.split("-")[0].trim();
        String materia2 = archivo.split("-")[1].trim();
        String docente2 = archivo.split("-")[2].trim();
        
        //Al cargar los archivos, los label en el panel de información mostrarán la información correspondiente-
        //según el código que a continuación se encuentra.
        LabelMateria1.setText("Materia: "+materia2.toUpperCase());
        LabelSeccion1.setText("Seccion: "+seccion2.toUpperCase());
        LabelDocente1.setText("Docente: "+docente2.toUpperCase());
        
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)Tabla2.getModel();
            
            //Se borran las filas previas al cargar una tabla nueva.
            model.setRowCount(0);
            
            //Se obtienen las líneas del txt.
            Object[] tableLines = br.lines().toArray();
            
            //Se carga la información de las líneas del .txt y se carga esta misma información a la tabla.
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                //El separador de la información en las líneas es el carácter "/".
                String[] dataRow = line.split("/");
                
                
                //Debug para ver qué llega de dataRow.
                for(String word : dataRow)
                {
                    System.out.println(word);
                }
                
                // Se agrega el promedio desde el DataRow
                promedios.add(Float.parseFloat(dataRow[4]));
                
                model.addRow(dataRow);
            }
            
            //En el código de a continuación se calcula el promedio de la sección y,-
            //además, se obtiene el % de alumnos aprobados.
            for(int i = 0;i<promedios.size();i++){
                
                float promedioActual = promedios.get(i);
                
                // Se suma al promedio de la sección el promedio actual del vector de promedios.
                promedioSeccion+=promedioActual;
                
                // Si el promedio actual es mayor igual a 10, entonces se le suma a los aprobados.
                if(promedioActual>=10) aprobados++;
                
            }
            // Se calcula el promedio con la suma obtenida y la cantidad de filas.
            promedioSeccion/=promedios.size();

            // Se calcula los aprobados de manera similar.
            aprobados = (aprobados/promedios.size())*100;
      
            //Se muestra el valor de la nota promedio de la sección y el % de aprobados.
            LabelPromedio1.setText("Promedio General: "+String.valueOf(promedioSeccion));
            LabelAprobados.setText("% de Aprobados: "+aprobados+"%");
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TextFileDataToJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_BCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCargar;
    private javax.swing.JButton BTabla;
    private javax.swing.JLabel Integrantes;
    private javax.swing.JLabel LabelAprobados;
    private javax.swing.JLabel LabelDocente1;
    private javax.swing.JLabel LabelMateria1;
    private javax.swing.JLabel LabelPromedio1;
    private javax.swing.JLabel LabelSeccion1;
    private javax.swing.JTextField NDocente;
    private javax.swing.JTextField NMateria;
    private javax.swing.JTextField NSeccion;
    private javax.swing.JPanel PanelControl;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel PanelTabla;
    private javax.swing.JTable Tabla2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logohub;
    // End of variables declaration//GEN-END:variables
}
